# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmon_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitordata',
            name='uid',
            field=models.CharField(blank=True, max_length=100, verbose_name='uid'),
        ),
    ]
